/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/vue-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as JwksRouteImport } from './routes/jwks'
import { Route as TokenRouteImport } from './routes/token'
import { Route as UserinfoRouteImport } from './routes/userinfo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component.vue'),
    'default',
  ),
})
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const JwksRoute = JwksRouteImport.update({
  id: '/jwks',
  path: '/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const UserinfoRoute = UserinfoRouteImport.update({
  id: '/userinfo',
  path: '/userinfo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/discovery': typeof DiscoveryRoute
  '/jwks': typeof JwksRoute
  '/token': typeof TokenRoute
  '/userinfo': typeof UserinfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/discovery': typeof DiscoveryRoute
  '/jwks': typeof JwksRoute
  '/token': typeof TokenRoute
  '/userinfo': typeof UserinfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/discovery': typeof DiscoveryRoute
  '/jwks': typeof JwksRoute
  '/token': typeof TokenRoute
  '/userinfo': typeof UserinfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/authorize' | '/discovery' | '/jwks' | '/token' | '/userinfo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authorize' | '/discovery' | '/jwks' | '/token' | '/userinfo'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/discovery'
    | '/jwks'
    | '/token'
    | '/userinfo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizeRoute: typeof AuthorizeRoute
  DiscoveryRoute: typeof DiscoveryRoute
  JwksRoute: typeof JwksRoute
  TokenRoute: typeof TokenRoute
  UserinfoRoute: typeof UserinfoRoute
}

declare module '@tanstack/vue-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwks': {
      id: '/jwks'
      path: '/jwks'
      fullPath: '/jwks'
      preLoaderRoute: typeof JwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/userinfo': {
      id: '/userinfo'
      path: '/userinfo'
      fullPath: '/userinfo'
      preLoaderRoute: typeof UserinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizeRoute: AuthorizeRoute,
  DiscoveryRoute: DiscoveryRoute,
  JwksRoute: JwksRoute,
  TokenRoute: TokenRoute,
  UserinfoRoute: UserinfoRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: lazyRouteComponent(
      () => import('./routes/__root.component.vue'),
      'default',
    ),
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/vue-start'
declare module '@tanstack/vue-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
